name: Laravel CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Установить PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'  # Укажите вашу версию PHP
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql
          coverage: none

      # Шаг 3: Установить зависимости Composer
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      # Шаг 4: Запустить PHPStan
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=2G

      # Опционально: Запустить тесты
#      - name: Run Tests
#        run: |
#          cp .env.example .env.test
#          php artisan key:generate
#          vendor/bin/phpunit --testdox

#      - name: Deploy via SSH
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          password: ${{ secrets.SSH_PASSWORD }}  # или key: ${{ secrets.SSH_KEY }}
#          port: ${{ secrets.SSH_PORT || 9999 }}
#
#          script: |
#            cd www/valsy.ru/Laravel/my-blog-12/
#            git pull origin main
#            composer install --no-dev --optimize-autoloader
#            php artisan migrate --force
#            php artisan config:cache
#            php artisan route:cache
#            php artisan view:cache
